- app/build.gradle
- app/src/androidTest/java/org/elastos/hive/HiveTest.java
- app/src/main/AndroidManifest.xml
- app/src/main/java/org/elastos/hive/HttpAPI.java
- app/src/main/java/org/elastos/hive/Node.java
- app/src/main/java/org/elastos/hive/NodeCmd.java
Implement the interfaces and add the test cases.
> Implement the interfaces and add the test cases.

- app/build.gradle
- app/src/androidTest/java/org/elastos/hive/HiveTest.java
- app/src/main/java/org/elastos/hive/HttpAPI.java
- app/src/main/java/org/elastos/hive/Node.java
- app/src/main/java/org/elastos/hive/NodeCmd.java
1. Implement the Hive's interfaces; 
2. Update the test cases.
> Implement the Hive's interfaces

- src/main/java/org/elastos/hive/AuthHelper.java
- src/main/java/org/elastos/hive/HiveFile.java
- src/main/java/org/elastos/hive/exceptions/HiveException.java
- src/main/java/org/elastos/hive/vendors/onedrive/OneDrive.java
- src/main/java/org/elastos/hive/vendors/onedrive/OneDriveAuthHelper.java
- src/main/java/org/elastos/hive/vendors/onedrive/OneDriveFile.java
- src/test/java/org/elastos/hive/HiveDriveTest.java
Implement the Hive interfaces about OneDrive
> Implement the Hive interfaces about OneDrive

- src/main/java/org/elastos/hive/vendors/onedrive/OneDrive.java
- src/main/java/org/elastos/hive/vendors/onedrive/OneDriveFile.java
- src/test/java/org/elastos/hive/HiveDriveTest.java
Update the hive's interfaces:
1. copy
2. rename
> Update the hive's interfaces and test.

- src/main/java/org/elastos/hive/vendors/onedrive/OneDriveDirectory.java
- src/main/java/org/elastos/hive/vendors/onedrive/OneDriveFile.java
- src/test/java/org/elastos/hive/OneDriveDirectoryTest.java
- src/test/java/org/elastos/hive/OneDriveDriveTest.java
- src/test/java/org/elastos/hive/OneDriveFileTest.java
1. Add OneDriveFileTest; 
2. debug OneDriveDirectory and OneDriveFile.
> Debug OneDriveDirectory and OneDriveFile.

- src/main/java/org/elastos/hive/vendors/hiveIpfs/HiveIpfsClient.java
- src/main/java/org/elastos/hive/vendors/hiveIpfs/HiveIpfsDirectory.java
- src/main/java/org/elastos/hive/vendors/hiveIpfs/HiveIpfsDrive.java
- src/main/java/org/elastos/hive/vendors/hiveIpfs/HiveIpfsFile.java
- src/main/java/org/elastos/hive/vendors/hiveIpfs/HiveIpfsParameter.java
- src/main/java/org/elastos/hive/vendors/hiveIpfs/HiveIpfsUtils.java
- src/test/java/org/elastos/hive/IpfsClientTest.java
- src/test/java/org/elastos/hive/IpfsTestBase.java
1. Add some files about Ipfs; 
2. Add the testcase about IpfsClient.
> Add some files about Ipfs

- src/main/java/org/elastos/hive/vendors/hiveIpfs/HiveIpfsClient.java
- src/main/java/org/elastos/hive/vendors/hiveIpfs/HiveIpfsDirectory.java
- src/main/java/org/elastos/hive/vendors/hiveIpfs/HiveIpfsDrive.java
- src/main/java/org/elastos/hive/vendors/hiveIpfs/HiveIpfsFile.java
- src/main/java/org/elastos/hive/vendors/hiveIpfs/HiveIpfsUtils.java
- src/main/java/org/elastos/hive/vendors/onedrive/OneDriveDirectory.java
- src/test/java/org/elastos/hive/IpfsDirectoryTest.java
- src/test/java/org/elastos/hive/IpfsDriveTest.java
1. Implement the interfaces about HiveIpfsDrive: createDirectory, getDirectroy and so on; 
2. Add the testcase about IpfsDrive.
> Implement the interfaces about HiveIpfsDrive

- src/main/java/org/elastos/hive/vendors/ipfs/IPFSClient.java
- src/main/java/org/elastos/hive/vendors/ipfs/IPFSDirectory.java
- src/main/java/org/elastos/hive/vendors/ipfs/IPFSDrive.java
- src/main/java/org/elastos/hive/vendors/ipfs/IPFSFile.java
- src/main/java/org/elastos/hive/vendors/ipfs/IPFSUtils.java
- src/test/java/org/elastos/hive/IpfsDirectoryTest.java
- src/test/java/org/elastos/hive/IpfsFileTest.java
1. Implement the interfaces about IPFSDirectory and IPFSFile; 
2. Add the testcases about IPFSDirectory and IPFSFile.
3. Add a internal method IPFSUtil.initialize to valid ipfs ip.
> Implement the interfaces about IPFSDirectory and IPFSFile

- src/main/java/org/elastos/hive/vendors/ipfs/IPFSClient.java
- src/main/java/org/elastos/hive/vendors/ipfs/IPFSParameter.java
- src/main/java/org/elastos/hive/vendors/ipfs/IPFSUtils.java
- src/test/java/org/elastos/hive/IpfsTestBase.java
1. Save the uid by using the new format; 
2. Add a dataPath parameter for the IPFSParameter constructor.
> Save the uid by using the new format

- src/main/java/org/elastos/hive/Client.java
- src/main/java/org/elastos/hive/vendors/ipfs/IPFSClient.java
- src/main/java/org/elastos/hive/vendors/ipfs/IPFSDirectory.java
- src/main/java/org/elastos/hive/vendors/ipfs/IPFSDrive.java
- src/main/java/org/elastos/hive/vendors/ipfs/IPFSEntry.java
- src/main/java/org/elastos/hive/vendors/ipfs/IPFSFile.java
- src/main/java/org/elastos/hive/vendors/ipfs/IPFSHelper.java
- src/main/java/org/elastos/hive/vendors/ipfs/IPFSMethod.java
- src/main/java/org/elastos/hive/vendors/ipfs/IPFSParameter.java
- src/main/java/org/elastos/hive/vendors/ipfs/IPFSURL.java
- src/main/java/org/elastos/hive/vendors/ipfs/IPFSUtils.java
- src/test/java/org/elastos/hive/IpfsClientTest.java
- src/test/java/org/elastos/hive/IpfsTestBase.java
Invoke the check codes before calling the interfaces about IPFS
> Invoke the check codes before calling the interfaces about IPFS

- src/main/java/org/elastos/hive/AuthToken.java
- src/main/java/org/elastos/hive/vendors/onedrive/OneDriveAuthHelper.java
- src/main/java/org/elastos/hive/vendors/onedrive/OneDriveClient.java
- src/main/java/org/elastos/hive/vendors/onedrive/OneDriveDirectory.java
- src/main/java/org/elastos/hive/vendors/onedrive/OneDriveDrive.java
- src/main/java/org/elastos/hive/vendors/onedrive/OneDriveFile.java
- src/main/java/org/elastos/hive/vendors/onedrive/OneDriveHttpHeader.java
Set expired if the http return code 401.
> Set expired if the http return code 401.

- build.gradle
- src/main/java/org/elastos/hive/AuthToken.java
- src/main/java/org/elastos/hive/JsonPersistent.java
- src/main/java/org/elastos/hive/Persistent.java
- src/main/java/org/elastos/hive/vendors/onedrive/OneDriveAuthHelper.java
- src/main/java/org/elastos/hive/vendors/onedrive/OneDriveClient.java
- src/main/java/org/elastos/hive/vendors/onedrive/OneDriveParameter.java
- src/main/java/org/elastos/hive/vendors/onedrive/OneDriveUtils.java
- src/test/java/org/elastos/hive/IpfsDirectoryTest.java
- src/test/java/org/elastos/hive/IpfsFileTest.java
- src/test/java/org/elastos/hive/OneDriveDirectoryTest.java
- src/test/java/org/elastos/hive/OneDriveFileTest.java
- src/test/java/org/elastos/hive/OneDriveTestBase.java
1. Save the login information about OneDrive; 
2. Clear the local data when logout; 
3. If the local information is valid, use it when the user login.
> Save the login information about OneDrive

- src/main/java/org/elastos/hive/vendors/onedrive/Constance.java
- src/main/java/org/elastos/hive/vendors/onedrive/Model/BaseServiceConfig.java
- src/main/java/org/elastos/hive/vendors/onedrive/OneDriveAuthHelper.java
- src/main/java/org/elastos/hive/vendors/onedrive/OneDriveClient.java
- src/main/java/org/elastos/hive/vendors/onedrive/OneDriveDirectory.java
- src/main/java/org/elastos/hive/vendors/onedrive/OneDriveDrive.java
- src/main/java/org/elastos/hive/vendors/onedrive/OneDriveFile.java
- src/main/java/org/elastos/hive/vendors/onedrive/network/BaseServiceUtil.java
- src/test/java/org/elastos/hive/OneDrive/OneDriveClientTest.java
- src/test/java/org/elastos/hive/OneDrive/OneDriveDirectoryTest.java
- src/test/java/org/elastos/hive/OneDrive/OneDriveDriveTest.java
- src/test/java/org/elastos/hive/OneDrive/OneDriveFileTest.java
- src/test/java/org/elastos/hive/OneDrive/OneDriveLoginTest.java
- src/test/java/org/elastos/hive/OneDrive/OneDriveTestBase.java
1.Move the onedrive test case to a separate folder
2.update BaseServiceConfig constructor
> Perfect “Improve code implement for OneDrive backend"

- src/main/java/org/elastos/hive/vendors/onedrive/OneDriveAuthHelper.java
- src/main/java/org/elastos/hive/vendors/onedrive/OneDriveClient.java
Fixed the bug about storing local data about OneDrive.
> Fixed the bug about storing local data about OneDrive

- src/main/java/org/elastos/hive/vendors/onedrive/CacheHelper.java
- src/main/java/org/elastos/hive/vendors/onedrive/OneDriveAuthHelper.java
- src/main/java/org/elastos/hive/vendors/onedrive/OneDriveClient.java
- src/main/java/org/elastos/hive/vendors/onedrive/OneDriveFile.java
- src/main/java/org/elastos/hive/vendors/onedrive/network/Api.java
- src/main/java/org/elastos/hive/vendors/onedrive/network/HeaderInterceptor.java
- src/test/java/org/elastos/hive/OneDrive/OneDriveFileOperatorTest.java
Implement the write and read interfaces about OneDrive.
> Implement the write and read interfaces about OneDrive.

- src/main/java/org/elastos/hive/vendors/ipfs/IPFSConstance.java
- src/main/java/org/elastos/hive/vendors/ipfs/IPFSDirectory.java
- src/main/java/org/elastos/hive/vendors/ipfs/IPFSDrive.java
- src/main/java/org/elastos/hive/vendors/onedrive/OneDriveDirectory.java
- src/main/java/org/elastos/hive/vendors/onedrive/OneDriveDrive.java
- src/main/java/org/elastos/hive/vendors/onedrive/network/Model/FileOrDirPropResponse.java
- src/test/java/org/elastos/hive/OneDrive/OneDriveDriveTest.java
- src/test/java/org/elastos/hive/ipfs/IpfsDriveTest.java
Implement the interface getItemInfo about OneDrive and IPFS.
> Implement the interface getItemInfo about OneDrive and IPFS

- src/main/java/org/elastos/hive/Directory.java
- src/main/java/org/elastos/hive/File.java
- src/main/java/org/elastos/hive/vendors/ipfs/IPFSDirectory.java
- src/main/java/org/elastos/hive/vendors/ipfs/IPFSDrive.java
- src/main/java/org/elastos/hive/vendors/ipfs/IPFSFile.java
- src/main/java/org/elastos/hive/vendors/onedrive/OneDriveDirectory.java
- src/main/java/org/elastos/hive/vendors/onedrive/OneDriveDrive.java
- src/main/java/org/elastos/hive/vendors/onedrive/OneDriveFile.java
- src/main/java/org/elastos/hive/vendors/onedrive/network/OneDriveApi.java
- src/test/java/org/elastos/hive/OneDrive/OneDriveDirectoryTest.java
- src/test/java/org/elastos/hive/OneDrive/OneDriveDriveTest.java
- src/test/java/org/elastos/hive/OneDrive/OneDriveFileTest.java
- src/test/java/org/elastos/hive/ipfs/IpfsDirectoryTest.java
- src/test/java/org/elastos/hive/ipfs/IpfsDriveTest.java
- src/test/java/org/elastos/hive/ipfs/IpfsFileTest.java
Fill the properties about File.Info and Directory.Info on IPFS and OneDrive.
> Fill the properties about File.Info and Directory.Info

- src/main/java/org/elastos/hive/vendors/connection/HeaderInterceptor.java
- src/main/java/org/elastos/hive/vendors/ipfs/IPFSFile.java
- src/main/java/org/elastos/hive/vendors/ipfs/IPFSRpcHelper.java
- src/main/java/org/elastos/hive/vendors/ipfs/network/IPFSApi.java
- src/test/java/org/elastos/hive/ipfs/IpfsDirectoryTest.java
1. Fixed the bug about ipfs read interface; 
2. optimize the ipfs commit interface; 
3. optimize the test case about getChildren on ipfs.
> Fixed the bug about ipfs read interface

- README.md
- build.gradle
- src/main/java/org/elastos/hive/Directory.java
1.Update 'How to use API'
2.update travis-ci address for Display icon
> Improve README:

- src/main/java/org/elastos/hive/vendors/onedrive/OneDriveAuthHelper.java
- src/main/java/org/elastos/hive/vendors/onedrive/OneDriveClient.java
- src/main/java/org/elastos/hive/vendors/onedrive/OneDriveDirectory.java
- src/main/java/org/elastos/hive/vendors/onedrive/OneDriveDrive.java
- src/main/java/org/elastos/hive/vendors/onedrive/network/OneDriveApi.java
- src/test/java/org/elastos/hive/OneDrive/OneDriveClientTest.java
- src/test/java/org/elastos/hive/OneDrive/OneDriveDirectoryTest.java
1. Update the testCase about OnedriveClient' getInfo; 
2. Throw the exception when login invalid.
> Throw the exception when login invalid

- src/main/java/org/elastos/hive/vendors/ipfs/IPFSClient.java
- src/main/java/org/elastos/hive/vendors/ipfs/IPFSDrive.java
- src/main/java/org/elastos/hive/vendors/onedrive/OneDriveClient.java
- src/main/java/org/elastos/hive/vendors/onedrive/OneDriveDrive.java
- src/test/java/org/elastos/hive/OneDrive/OneDriveDirectoryTest.java
- src/test/java/org/elastos/hive/OneDrive/OneDriveDriveTest.java
- src/test/java/org/elastos/hive/ipfs/IpfsDriveTest.java
Fixed the bug about OneDriveDrive's getLastInfo
> Fixed the bug about OneDriveDrive's getLastInfo.

- build.gradle
- src/main/java/org/elastos/hive/Directory.java
- src/main/java/org/elastos/hive/Drive.java
- src/main/java/org/elastos/hive/File.java
- src/main/java/org/elastos/hive/HiveException.java
- src/main/java/org/elastos/hive/IPFSEntry.java
- src/main/java/org/elastos/hive/OAuthEntry.java
- src/main/java/org/elastos/hive/vendors/ipfs/IPFSParameter.java
- src/main/java/org/elastos/hive/vendors/onedrive/OneDriveParameter.java
1.Add IPFSParameter and OneDriveParameter annotation. 
2.Update build javadoc config .
> Fix javadoc

- src/main/java/org/elastos/hive/vendors/ipfs/IPFSClient.java
- src/main/java/org/elastos/hive/vendors/ipfs/IPFSFile.java
- src/main/java/org/elastos/hive/vendors/onedrive/OneDriveAuthHelper.java
- src/main/java/org/elastos/hive/vendors/onedrive/OneDriveClient.java
- src/main/java/org/elastos/hive/vendors/onedrive/OneDriveDirectory.java
- src/main/java/org/elastos/hive/vendors/onedrive/OneDriveDrive.java
- src/main/java/org/elastos/hive/vendors/onedrive/OneDriveFile.java
Fixed the bug about the callback of read and write interfaces
> Fixed the bug about the callback of read and write interfaces.

- build.gradle
> Feat_uploadMaven

- src/main/java/org/elastos/hive/vendors/ipfs/IPFSFile.java
- src/main/java/org/elastos/hive/vendors/onedrive/OneDriveFile.java
- src/test/java/org/elastos/hive/OneDrive/OneDriveDirectoryTest.java
- src/test/java/org/elastos/hive/OneDrive/OneDriveDriveTest.java
- src/test/java/org/elastos/hive/OneDrive/OneDriveFileOperatorTest.java
- src/test/java/org/elastos/hive/ipfs/IpfsDirectoryTest.java
- src/test/java/org/elastos/hive/ipfs/IpfsDriveTest.java
- src/test/java/org/elastos/hive/ipfs/IpfsFileOperatorTest.java
Add the testcases with callback about the write/read interfaces
> Add the testcases with callback about the write/read interfaces.

- src/main/java/org/elastos/hive/vendors/onedrive/OneDriveDirectory.java
- src/main/java/org/elastos/hive/vendors/onedrive/network/OneDriveApi.java
- src/test/java/org/elastos/hive/OneDrive/OneDriveRootDirTest.java
Fixed the bug about createDirectory for root at the OneDrive
> Fixed the bug about createDirectory for root at the OneDrive.

- src/main/java/org/elastos/hive/vendors/ipfs/IPFSFile.java
- src/main/java/org/elastos/hive/vendors/onedrive/OneDriveFile.java
- src/test/java/org/elastos/hive/OneDrive/OneDriveFileOperatorTest.java
Fixed the bug about read/write
> Fixed the bug about read/write

- src/main/java/org/elastos/hive/vendors/ipfs/IPFSClient.java
- src/main/java/org/elastos/hive/vendors/ipfs/IPFSDirectory.java
- src/main/java/org/elastos/hive/vendors/ipfs/IPFSDrive.java
- src/main/java/org/elastos/hive/vendors/ipfs/IPFSFile.java
- src/main/java/org/elastos/hive/vendors/ipfs/IPFSRpcHelper.java
- src/test/java/org/elastos/hive/OneDrive/OneDriveDriveTest.java
- src/test/java/org/elastos/hive/ipfs/IpfsCheckUid.java
- src/test/java/org/elastos/hive/ipfs/IpfsDirectoryTest.java
- src/test/java/org/elastos/hive/ipfs/IpfsDriveTest.java
- src/test/java/org/elastos/hive/ipfs/IpfsFileOperatorTest.java
- src/test/java/org/elastos/hive/ipfs/IpfsFileTest.java
Fixed about the invoke-callback process on IPFS
> Fixed about the invoke-callback process on IPFS.

- src/main/java/org/elastos/hive/vendors/onedrive/OneDriveClient.java
- src/main/java/org/elastos/hive/vendors/onedrive/OneDriveDirectory.java
- src/main/java/org/elastos/hive/vendors/onedrive/OneDriveDrive.java
- src/main/java/org/elastos/hive/vendors/onedrive/network/OneDriveApi.java
Rename name about some inter-methods
> Rename name about some inter-methods.

- src/test/java/org/elastos/hive/ipfs/IpfsDirectoryTest.java
- src/test/java/org/elastos/hive/ipfs/IpfsDriveTest.java
- src/test/java/org/elastos/hive/ipfs/IpfsFileOperatorTest.java
- src/test/java/org/elastos/hive/ipfs/IpfsFileTest.java
Optimize the testcases about file/dir.deleteItem
> Optimize the testcases about file/dir.deleteItem.

- src/main/java/org/elastos/hive/utils/LogUtil.java
- src/main/java/org/elastos/hive/vendors/ipfs/IPFSDirectory.java
- src/main/java/org/elastos/hive/vendors/ipfs/IPFSFile.java
- src/main/java/org/elastos/hive/vendors/onedrive/OneDriveDirectory.java
- src/main/java/org/elastos/hive/vendors/onedrive/OneDriveDrive.java
- src/main/java/org/elastos/hive/vendors/onedrive/OneDriveFile.java
- src/main/java/org/elastos/hive/vendors/onedrive/network/OneDriveApi.java
- src/main/java/org/elastos/hive/vendors/onedrive/network/model/FileOrDirPropResponse.java
- src/main/java/org/elastos/hive/vendors/onedrive/network/model/UploadSessionResponse.java
- src/test/java/org/elastos/hive/OneDrive/OneDriveFileTest.java
- src/test/java/org/elastos/hive/ipfs/IpfsFileTest.java
Implement and debug upload large file about oneDriveFile.
> Implement and debug upload large file about oneDriveFile

- src/main/java/org/elastos/hive/Vault.java
> CU-emu192: format improvement for Vault.java - use tab (size: 4) instead of whitespaces.

- src/main/java/org/elastos/hive/vault/AuthHelper.java
formatting Vault.java - use tab (size: 4) instead of whitespace to keep indent aligned.
> CU-eptuvy: formatting Vault.java - use tab (size: 4) instead of whitespace to keep indent aligned.

- src/main/java/org/elastos/hive/AuthHelper.java
- src/main/java/org/elastos/hive/DatabaseClient.java
- src/main/java/org/elastos/hive/FilesClient.java
- src/main/java/org/elastos/hive/database/DocCount.java
- src/main/java/org/elastos/hive/files/FileHash.java
- src/main/java/org/elastos/hive/files/FilesList.java
- src/main/java/org/elastos/hive/files/UploadOutputStream.java
- src/main/java/org/elastos/hive/network/NodeApi.java
- src/main/java/org/elastos/hive/network/model/AuthResponse.java
- src/main/java/org/elastos/hive/network/model/CountDocResponse.java
- src/main/java/org/elastos/hive/network/model/SignResponse.java
- src/main/java/org/elastos/hive/network/model/UploadResponse.java
code review and code refactoring
> Fix branch

- src/main/java/org/elastos/hive/DatabaseImpl.java
- src/main/java/org/elastos/hive/FilesImpl.java
- src/main/java/org/elastos/hive/PaymentImpl.java
- src/main/java/org/elastos/hive/ScriptingImpl.java
- src/main/java/org/elastos/hive/Vault.java
- src/main/java/org/elastos/hive/VersionImpl.java
> CU-g4rb35 - rename all Java Client with XXXClient.java to be xxxImpl.java

- src/main/java/org/elastos/hive/Client.java
- src/main/java/org/elastos/hive/PaymentImpl.java
- src/main/java/org/elastos/hive/payment/Order.java
- src/main/java/org/elastos/hive/payment/UsingPlan.java
1.check exception
2.fix getAllOrders problem
> Improve branch

- src/main/java/org/elastos/hive/auth/LocalResolver.java
- src/main/java/org/elastos/hive/auth/RemoteResolver.java
- src/main/java/org/elastos/hive/auth/TokenResolver.java
- src/main/java/org/elastos/hive/connection/RequestInterceptor.java
> Improve internal method implementation for localResolver to acquire token.

- src/main/java/org/elastos/hive/service/DatabaseService.java
- src/main/java/org/elastos/hive/vault/DatabaseServiceRender.java
- src/main/java/org/elastos/hive/vault/database/DatabaseAPI.java
- src/main/java/org/elastos/hive/vault/database/DatabaseController.java
- src/main/java/org/elastos/hive/vault/database/InsertOptions.java
- src/main/java/org/elastos/hive/vault/database/InsertResult.java
- src/test/java/org/elastos/hive/DatabaseServiceTest.java
- src/test/java/org/elastos/hive/ScriptingCrossingTest.java
- src/test/java/org/elastos/hive/ScriptingServiceTest.java
> CU-8tvure - improving DatabaseService and ScriptingService internal implementation
